---
- id: skjold
  name: skjold
  description: Security audit Python project dependencies against security advisory databases.
  entry: skjold audit
  language: python
  language_version: python3
  require_serial: true
  verbose: true
  always_run: true
  files: ^(poetry\.lock|Pipfile\.lock|requirements.*\.txt)$
